### PR TITLE
reformat cooldown error message

### PR DESCRIPTION
**Pull request by Dekriel**

### CODE REVIEW

**Comment by Yat-o** [comment]
I see no point of building the embed and binding it to a variable that you use once. Just build the embed inside the send method. Making one use variables takes up unnecessary memory.

**Comment by Dekriel** [comment]
ok

**Comment by Robin5605** [comment]
I say we keep the variable for readability. It uses up such little memory it's negligible. I also suggest you reformat the `title` variable to be like so:

```py
title = [
    ...,
    ...,
    ...,
]
```
Also for readability.

**Review by Robin5605 — APPROVED** [review]

**Comment by Yat-o** [comment]
That may be so. But neglecting any optimization is substandard. Also in most commands and methods we've already gone with building the embed in the send method. So the change wouldn’t be just for a small amount of optimization but code base consistency as well.

**Review by Pandabweer — APPROVED** [review]
Looks good to me :)
We will think about a more better solution to random responses later on.

**Comment by Dekriel** [comment]
thanks for the reviews, will keep in mind to reduce unnecessary memory in the future.

**Pull request merged**
