### PR TITLE
Pylint seeing cogs as modules

### PR DESCRIPTION
**Pull request by Pandabweer**
Pylint is not having it's greatest moments since it tries to pip install the cogs. Resulting in errors.

### CODE REVIEW

**Comment by Robin5605** [comment]
And you're sure the removal of `pylint.yml` does not break anything else?

**Comment by osam7a** [comment]
try to use `from . import <cog name>`
if not try `from <folder> import <cog name>`

**Comment by Pandabweer** [comment]
> And you're sure the removal of `pylint.yml` does not break anything else?

Pretty sure since i added it then now made a pr to remove it.

**Review by kaylebetter — APPROVED** [review]

**Comment by NotFlameDev** [comment]
Do we really need to remove pylint entirely? I'm sure there is a fix for it. There are many related issues on Google.

**Comment by Pandabweer** [comment]
Going to close since no one is looking at it.

**Pull request closed without merging**
