### PR TITLE
Add googlesearch

### PR DESCRIPTION
**Pull request by Infernum1**

### CODE REVIEW

**Comment by Pandabweer** [comment]
Why would you add a new import for this?

**Comment by Infernum1** [comment]
> Why would you add a new import for this?

because it required the package lmao

**Comment by Pandabweer** [comment]
Well i don't like it but ig Caeden is a fan of it, edit the PR and add it to the requirments.txt ig.

**Comment by Infernum1** [comment]
> Well i don't like it but ig Caeden is a fan of it, edit the PR and add it to the requirments.txt ig.
>  

Can't do that atm cause I got off pc, will do tommorow

**Pull request merged**
