### PR TITLE
Alias IDE

### PR DESCRIPTION
**Pull request by osam7a**

### CODE REVIEW

**Review by Robin5605 — APPROVED** [review]

**Review by Yat-o — CHANGES_REQUESTED** [review]
That help string is way too long(PEP8 line length limit = 79). Also we're not using `help` either. We're using doc strings for command descriptions.

**Comment by osam7a** [comment]
i wasnt the one who made the help string bruh, i just made the alias

**Comment by Yat-o** [comment]
if you remove it and add it to a doc string and commit. I’ll approve pr. Pls and thx

**Comment by osam7a** [comment]
but i didnt even make the help string wt, i just added a coma at the end and it shows that i changed it

**Review by Yat-o — APPROVED** [review]

**Pull request merged**
