### PR TITLE
Improvement in Error Handling , Fixed Help Command , Made reason for Unban command not required

### PR DESCRIPTION
**Pull request by sarthak-py**
Any user was able to use SelectMenu , irrespective of the command author in the help command , `unban` had a required argument `reason` ,

### CODE REVIEW

**Review by CaedenPH — APPROVED** [review]
awesome work

**Comment by NotFlameDev** [comment]
The rest are fine

**Comment by sarthak-py** [comment]
> The rest are fine

 why does it appears as 9 more content but only 1 when opened

**Review by Yat-o — APPROVED** [review]
Good work and good catch as well.

**Pull request merged**
