### PR TITLE
fixing the link issue with the calculator and making the code more cleaner 

### PR DESCRIPTION
**Pull request by realstealthninja**
### Fixes
- merging the if statements in bot.py line 109
- fixing the issue where if you send a link which contains any "mathematical equations" the calculator opens
- removing alot of unused imports

#### feels good to finally contribute, more fixes and code coming soon

### CODE REVIEW

**Comment by realstealthninja** [comment]
I will fix this today

**Review by sifte — APPROVED** [review]

**Comment by RopraMMC** [comment]
I approve

**Comment by realstealthninja** [comment]
> I approve

thank you ropra very cool 👍

**Review by Yat-o — APPROVED** [review]
Lgtm

**Pull request merged**
